global:
  scrape_interval:     90s
  evaluation_interval: 90s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 30s
    static_configs:
      - targets: ['to.be.monitored:9100']

  - job_name: 'cadvisor'
    scrape_interval: 30s
    static_configs:
      - targets: ['to.be.monitored:8080']
